Check1/Models/Student.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Check1.Data.Base;
using Check1.Data.Enums;

namespace Check1.Models
{
    public class Student : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        /*public int DepartmentId { get; set; }
        [ForeignKey("DepartmentId")]
        public Department Department { get; set; }
        */
        public List<StudentAttendance>? StudentAttendances { get; set; }
        public List<Student_Course>? Student_Courses { get; set; }
        public List<Book>? Books { get; set; }
    }
}

Check1/Controllers/CoursesController.cs
using Check1.Data.Services;
using Check1.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Check1.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICoursesService _service;

        public CoursesController(ICoursesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCourses = await _service.GetAllAsync();
            //n => n.Cinema
            return View(allCourses);
        }

        /*[AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allCourses = await _service.GetAllAsync();
            //n => n.Cinema
            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allCourses.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allCourses.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allCourses);
        }
        */
        //GET: Courses/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var CourseDetail = await _service.GetCourseByIdAsync(id);
            return View(CourseDetail);
        }

        //GET: Courses/Create
        public async Task<IActionResult> Create()
        {
            var CourseDropdownsData = await _service.GetNewCourseDropdownsValues();
            ViewBag.Students = new SelectList(CourseDropdownsData.Students, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewCourseVM Course)
        {
            if (!ModelState.IsValid)
            {
                var CourseDropdownsData = await _service.GetNewCourseDropdownsValues();
                ViewBag.Students = new SelectList(CourseDropdownsData.Students, "Id", "Name");

                return View(Course);
            }

            await _service.AddNewCourseAsync(Course);
            return RedirectToAction(nameof(Index));
        }


        //GET: Courses/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var CourseDetails = await _service.GetCourseByIdAsync(id);
            if (CourseDetails == null) return View("NotFound");

            var response = new NewCourseVM()
            {
                Id = CourseDetails.Id,
                Name = CourseDetails.Name,
                Description = CourseDetails.Description,
                MaxMarks=CourseDetails.MaxMarks,
                PassMarks=CourseDetails.PassMarks,
                StudentIds = CourseDetails.Student_Courses.Select(n => n.StudentId).ToList(),
            };

            var CourseDropdownsData = await _service.GetNewCourseDropdownsValues();
            ViewBag.Students = new SelectList(CourseDropdownsData.Students, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewCourseVM Course)
        {
            if (id != Course.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var CourseDropdownsData = await _service.GetNewCourseDropdownsValues();
                ViewBag.Students = new SelectList(CourseDropdownsData.Students, "Id", "Name");

                return View(Course);
            }

            await _service.UpdateCourseAsync(Course);
            return RedirectToAction(nameof(Index));
        }
    }
}

Check1/Controllers/DepartmentsController.cs
using Check1.Data;
using Check1.Data.Services;
using Check1.Data.ViewModels;
using Check1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Check1.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentsService _service;

        public DepartmentsController(IDepartmentsService service)
        {
            _service = service;
        }

      
        public async Task<IActionResult> Index()
        {
            var allDepartments = await _service.GetAllAsync();
            return View(allDepartments);
        }


        //Get: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewDepartmentVM department)
        {

           if (!ModelState.IsValid) return View(department);
            await _service.AddNewDepartmentAsync(department);
            return RedirectToAction(nameof(Index));
        }
        /*[HttpPost]
        public async Task<IActionResult> Create(string name)
        {

            Department department = new Department();
            try
            {
                department.Name = name;
            }catch(Exception e) { return View(department); }
            //if (!ModelState.IsValid) return View(department);
            await _service.AddAsync(department);
            return RedirectToAction(nameof(Index));
        }*/

        //Get: Departments/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var departmentDetails = await _service.GetDepartmentByIdAsync(id);
            if (departmentDetails == null) return View("NotFound");
            return View(departmentDetails);
        }

        //Get: Departments/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var departmentDetails = await _service.GetDepartmentByIdAsync(id);
            if (departmentDetails == null) return View("NotFound");
            return View(departmentDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewDepartmentVM department)
        {
            if (id != department.Id) return View("NotFound");
            if (!ModelState.IsValid) return View(department);
            await _service.UpdateDepartmentAsync(department);
            return RedirectToAction(nameof(Index));
        }

        //Get: Departments/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var departmentDetails = await _service.GetByIdAsync(id);
            if (departmentDetails == null) return View("NotFound");
            return View(departmentDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var departmentDetails = await _service.GetByIdAsync(id);
            if (departmentDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Check1/Controllers/StudentsController.cs
using Check1.Data.Services;
using Check1.Data.ViewModels;
using Check1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Check1.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentsService _service;

        public StudentsController(IStudentsService service)
        {
            _service = service;
        }


        public async Task<IActionResult> Index()
        {
            var allStudents = await _service.GetAllAsync();
            //n => n.Course
            return View(allStudents);
        }

        /*
        public async Task<IActionResult> Filter(string searchString)
        {
            var allStudents = await _service.GetAllAsync(n => n.Department);

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allStudents.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allStudents.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allStudents);
        }*/

        //GET: Students/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var StudentDetail = await _service.GetStudentByIdAsync(id);
            return View(StudentDetail);
        }

        //GET: Students/Create
        public async Task<IActionResult> Create()
        {
            var StudentDropdownsData = await _service.GetNewStudentDropdownsValues();

            ViewBag.Courses = new SelectList(StudentDropdownsData.Courses, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewStudentVM Student)
        {
            if (!ModelState.IsValid)
            {
                var StudentDropdownsData = await _service.GetNewStudentDropdownsValues();

                ViewBag.Courses = new SelectList(StudentDropdownsData.Courses, "Id", "Name");
                return View(Student);
            }

            await _service.AddNewStudentAsync(Student);
            return RedirectToAction(nameof(Index));
        }


        //GET: Students/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var StudentDetails = await _service.GetStudentByIdAsync(id);
            if (StudentDetails == null) return View("NotFound");

            var response = new NewStudentVM()
            {
                Id = StudentDetails.Id,
                Name = StudentDetails.Name,
                CourseIds = StudentDetails.Student_Courses.Select(n => n.CourseId).ToList(),
            };

            var StudentDropdownsData = await _service.GetNewStudentDropdownsValues();
            ViewBag.Courses = new SelectList(StudentDropdownsData.Courses, "Id", "Name");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewStudentVM Student)
        {
            if (id != Student.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var StudentDropdownsData = await _service.GetNewStudentDropdownsValues();

                ViewBag.Courses = new SelectList(StudentDropdownsData.Courses, "Id", "Name");
                return View(Student);
            }

            await _service.UpdateStudentAsync(Student);
            return RedirectToAction(nameof(Index));
        }
    }
}

Check1/Views/Students/Create.cshtml
@model NewStudentVM
@using Check1.Data.ViewModels;
 
@{
    ViewData["Title"] = "Create a new Student";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Student</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                          
                        </div>
                        @*<div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DepartmentId" class="control-label"></label>
                                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.Departments"></select>
                                <span asp-validation-for="DepartmentId" class="text-danger"></span>
                            </div>

                            </div>*@
                  
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="CourseIds" class="control-label"></label>
                            <select asp-for="CourseIds" class="form-control" asp-items="ViewBag.Courses" multiple></select>
                            <span asp-validation-for="CourseIds" class="text-danger"></span>
                        </div>
                    </div>


                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

Check1/Views/Students/Details.cshtml
@model Student

@{
    ViewData["Title"] = "Student details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
              
                <div class="col-md-8">
                    <div class="card-body">
                       
                        @*<p class="card-text">
                            <b>Department: </b>
                            <a asp-controller="Departments" asp-action="Details" asp-route-id="@Model.DepartmentId">
                                @Model.Department.Name
                            </a>
                        </p>*@
                        <p class="card-text">
                            <b>Courses: </b>
                            <hr />
                            <div class="row">
                                @foreach (var course in Model.Student_Courses)
                                {
                                    <div class="column text-center">
                                        <a asp-controller="Courses" asp-action="Details" asp-route-id="@course.CourseId">@course.Course.Name</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                        
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Check1/Views/Students/Edit.cshtml
@model NewStudentVM
@using Check1.Data.ViewModels;
 
@{
    ViewData["Title"] = "Update Student";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Student</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                         
                        </div>
                        @*<div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DepartmentId" class="control-label"></label>
                                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.Departments"></select>
                                <span asp-validation-for="DepartmentId" class="text-danger"></span>
                            </div>
                          
                        </div>*@
                      
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="CourseIds" class="control-label"></label>
                            <select asp-for="CourseIds" class="form-control" asp-items="ViewBag.Courses" multiple></select>
                            <span asp-validation-for="CourseIds" class="text-danger"></span>
                        </div>
                    </div>


                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
      /*  $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageURL").val();
        });

        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })*/
    </script>
}

Check1/Views/Students/Index.cshtml
@model IEnumerable<Student>

@{
    ViewData["Title"] = "List of Students";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                </h5>
                            </p>
                        </div>
                    </div>
                 
                    <div class="col-md-6">
                        <div class="card-body">

                            @*<p class="card-text"><b>Department: </b>@item.Department.Name</p>
                           <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                        </p>*@

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                               @* <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                            <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>*@
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Students")